name: container-release

on:
  release:
    types:
      - created

env:
  REGISTRY_IMAGE: ghcr.io/onedr0p/coolbox

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=version::${GITHUB_REF##*/}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_IMAGE }}:${{ steps.prep.outputs.version }}
            ${{ env.REGISTRY_IMAGE }}:v${{ steps.prep.outputs.version }}
            ${{ env.REGISTRY_IMAGE }}:latest
          cache-from: type=registry,ref=ghcr.io/onedr0p/coolbox:latest
