name: container-pull-request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            ghcr.io/onedr0p/coolbox:${{github.event.number}}
          cache-from: type=registry,ref=ghcr.io/onedr0p/coolbox:buildcache
          cache-to: type=registry,ref=ghcr.io/onedr0p/coolbox:buildcache,mode=max
